GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/info


###
GET http://localhost:3001/unknown

###
GET http://localhost:3001/api/persons/2


###
GET http://localhost:3001/api/persons/5c41c90e84d891c15dfa3431



###
GET http://localhost:3001/api/persons/piipaa

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Kissa Kii",
    "number": "123-123123"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Arto Zellas",
    "number": "123-1231233"
}

###
PUT http://localhost:3001/api/persons/60dd50c21c268923b5ce1a04 HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "123-12312999"
}


###
PUT http://localhost:3001/api/persons/piipaapoo HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "123-12312999"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Kissa Kii"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "123-123123"
}

###
GET http://localhost:3001/api/persons/60dd51620f76f0240c7670f5


###
DELETE http://localhost:3001/api/persons/60dd525105c6d22459eec29e